universe = vanilla
execroot = /Volumes/DataX/Users/grogee/Documents/programming/hmmsort
executable = $(execroot)/run_hmm_decode.sh 
sortdir = hmmsort
tempfile = spike_templates.hdf5
outfile = hmmsort.mat
arguments = "/Applications/MATLAB_R2016b.app SourceFile $(fname) Group 1 fileName $(tempfile) save hdf5 SaveFile $(outfile)"
transfer_executable = yes 
should_transfer_files = yes
when_to_transfer_output = ON_EXIT
transfer_input_files = $(fname),$(tempfile), $(execroot)/hmm_decode.app
transfer_output_files = $(outfile)
output	=	$(sortdir)/hmm_decode.out
stream_output = true
error	=	$(sortdir)/hmm_decode.err
stream_error = true
log		=	$(sortdir)/hmm_decode.log
getenv  = true
request_memory=2G
RunAsOwner = false
queue 1 
